name: l3study
favicon: null
layout_spectrum: 0.81669
typography_spectrum: 0.3680307357572019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6242888462729752
  lightness: 0.9208011634182185
  saturation: 0.04476225981488824
  rhythmicContrast: 0.16846650396473706
purpose: []
