name: l3study
favicon: null
layout_spectrum: 0.85162
typography_spectrum: 0.3680307357572019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#5c5c5c'
    - '#9f9f9f'
    - '#c6c6c6'
    - '#ececec'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.04476225981488824
  rhythmicContrast: 0.75
purpose: []
